// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtsaiT5IwCuQmuJZ1q-Ek8SLLIsO0Ns1g',
    appId: '1:581846295143:web:8ae013cde591500adf6ac2',
    messagingSenderId: '581846295143',
    projectId: 'mobile-lab-flutter-fireb-aad72',
    authDomain: 'mobile-lab-flutter-fireb-aad72.firebaseapp.com',
    storageBucket: 'mobile-lab-flutter-fireb-aad72.appspot.com',
    measurementId: 'G-Q3CXHYK2GN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtAwSf1ueUPK8tXT8W-46QusXnYYiRt6Y',
    appId: '1:581846295143:android:2391a1ce5f8f42addf6ac2',
    messagingSenderId: '581846295143',
    projectId: 'mobile-lab-flutter-fireb-aad72',
    storageBucket: 'mobile-lab-flutter-fireb-aad72.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxkz4HscyFt6Mc2Plbj__fWhTn5b9TQmA',
    appId: '1:581846295143:ios:337d0986d363bde3df6ac2',
    messagingSenderId: '581846295143',
    projectId: 'mobile-lab-flutter-fireb-aad72',
    storageBucket: 'mobile-lab-flutter-fireb-aad72.appspot.com',
    iosClientId: '581846295143-1pbn6rbrkcnup3k8sihgu58pu3j24375.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxkz4HscyFt6Mc2Plbj__fWhTn5b9TQmA',
    appId: '1:581846295143:ios:337d0986d363bde3df6ac2',
    messagingSenderId: '581846295143',
    projectId: 'mobile-lab-flutter-fireb-aad72',
    storageBucket: 'mobile-lab-flutter-fireb-aad72.appspot.com',
    iosClientId: '581846295143-1pbn6rbrkcnup3k8sihgu58pu3j24375.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthen',
  );
}
